name: Generate OpenAPI Schema

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate Schema
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: cargo run --release

      - name: Commit generated Schema
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add schema.json

            if git diff --cached --quiet; then
                echo "No changes to commit"
                exit 0
            fi

            git commit -m "chore(schema): update generated API schema"
            git push